# Generated by Django 5.2.13 on 2026-04-11 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название кейса')),
                ('short_description', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cases/', verbose_name='Изображение кейса')),
                ('detail_url', models.CharField(blank=True, max_length=255, verbose_name='Ссылка "Читать подробнее"')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Кейс',
                'verbose_name_plural': 'Кейсы',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_background', models.ImageField(blank=True, null=True, upload_to='home/backgrounds/', verbose_name='Фоновое изображение страницы')),
                ('help_title', models.CharField(default='С чем я могу помочь', max_length=255, verbose_name='Заголовок блока помощи')),
                ('help_description', models.TextField(blank=True, verbose_name='Описание блока помощи')),
                ('about_title', models.CharField(default='Профессиональный подход и современная хирургия', max_length=255, verbose_name='Заголовок блока "Обо мне"')),
                ('about_text', models.TextField(blank=True, verbose_name='Текст блока "Обо мне"')),
                ('about_photo', models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='Фото врача')),
                ('cases_title', models.CharField(default='Примеры работ', max_length=255, verbose_name='Заголовок блока кейсов')),
                ('cases_description', models.TextField(blank=True, verbose_name='Описание блока кейсов')),
                ('clinic_title', models.CharField(default='Где проходит приём', max_length=255, verbose_name='Заголовок блока клиники')),
                ('clinic_description', models.TextField(blank=True, verbose_name='Описание блока клиники')),
                ('clinic_map_embed', models.TextField(blank=True, verbose_name='HTML / iframe карты')),
                ('prices_title', models.CharField(default='Услуги и цены', max_length=255, verbose_name='Заголовок блока цен')),
                ('reviews_title', models.CharField(default='Что говорят пациенты', max_length=255, verbose_name='Заголовок блока отзывов')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Главная страница',
                'verbose_name_plural': 'Главная страница',
            },
        ),
        migrations.CreateModel(
            name='PriceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название услуги')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price_text', models.CharField(blank=True, max_length=100, verbose_name='Цена / подпись цены')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Услуга / цена',
                'verbose_name_plural': 'Услуги / цены',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=255, verbose_name='Имя пациента')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('source', models.CharField(blank=True, max_length=255, verbose_name='Источник')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('show_on_home', models.BooleanField(default=True, verbose_name='Показывать на главной')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/', verbose_name='Логотип / иконка')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('cta_text', models.CharField(default='Запись на приём', max_length=100, verbose_name='Текст кнопки записи')),
                ('doctor_name', models.CharField(blank=True, max_length=255, verbose_name='Имя и фамилия')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('telegram_url', models.URLField(blank=True, verbose_name='Ссылка на Telegram')),
                ('vk_url', models.URLField(blank=True, verbose_name='Ссылка на VK')),
                ('whatsapp_url', models.URLField(blank=True, verbose_name='Ссылка на WhatsApp')),
                ('privacy_policy_url', models.URLField(blank=True, verbose_name='Ссылка на политику конфиденциальности')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
    ]
