# Generated by Django 5.2.13 on 2026-04-11 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='hero_background',
            field=models.ImageField(blank=True, null=True, upload_to='homepage/', verbose_name='Фоновое изображение страницы'),
        ),
    ]
