# Generated by Django 5.2.13 on 2026-05-26 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sitesettings_max_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Название раздела')),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True, verbose_name='URL раздела')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Раздел для пациентов',
                'verbose_name_plural': 'Разделы для пациентов',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PatientPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True, verbose_name='URL страницы')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='patients/', verbose_name='Основная картинка')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('source_url', models.URLField(blank=True, verbose_name='Источник')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='core.patientcategory', verbose_name='Раздел')),
            ],
            options={
                'verbose_name': 'Страница для пациентов',
                'verbose_name_plural': 'Страницы для пациентов',
                'ordering': ['category__order', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PatientPageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название части')),
                ('content', models.TextField(verbose_name='Контент')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.patientpage', verbose_name='Страница')),
            ],
            options={
                'verbose_name': 'Часть страницы для пациентов',
                'verbose_name_plural': 'Части страниц для пациентов',
                'ordering': ['order', 'id'],
            },
        ),
    ]
